/**
 * Video Creation Workbench —
 * `GET /api/projects/{id}/composition/scenes/{compositionId}`.
 *
 * Returns a single scene's sub-composition HTML wrapped in a minimal host
 * document so an iframe renders the GSAP animation instead of a blank
 * `<template>`. The sub-composition files live under
 * `composition/compositions/{compositionId}.html` on disk and are the raw
 * LLM output for one scene; by themselves they don't render anything
 * because the `<template>` element is inert. This route stitches in:
 *   - a `<!DOCTYPE html>` host doc with a dark body and GSAP script tag,
 *   - a small DOMContentLoaded script that looks up the template by
 *     `{compositionId}-template` (the generator-appended id), clones its
 *     content into the body, re-creates cloned `<script>` elements so
 *     they actually execute (HTML spec: cloned scripts don't run), then
 *     plays the registered `window.__timelines[compositionId]` entry,
 * so a preview iframe can point at the URL and see the animation play.
 *
 * Error mapping:
 *   - Invalid project id         → 400 `INVALID_PROJECT_ID` (via helper).
 *   - Invalid compositionId shape → 400 `VALIDATION_FAILED`.
 *   - Missing sub-composition file → 404 `COMPOSITION_NOT_FOUND`.
 *   - Forbidden token in HTML    → 500 `UNKNOWN` (data-integrity bug; the
 *     composition pipeline should have rejected this before it hit disk).
 */

import fs from "node:fs/promises";

import type { NextRequest } from "next/server";

import {
  awaitParams,
  requireProjectIdFromParams,
  respondError,
} from "@/lib/workbench/api-helpers";
import { sql, isNeonConfigured } from "@/lib/db";
import { ErrorCode, WorkbenchError } from "@/lib/workbench/errors";
import { scanHtml } from "@/lib/workbench/html-scanner";
import { resolveProjectFile } from "@/lib/workbench/path-safety";

type Ctx = { params: Promise<{ id: string; compositionId: string }> };

/**
 * Sub-composition filename stem: `scene-{2-digit index}-{6 hex}`.
 * Deliberately narrower than `REGEX.SCENE_ID` because these are
 * composition filenames generated by the storyboard / composition pipeline,
 * not Scene identifiers.
 */
const COMPOSITION_ID_REGEX = /^scene-\d{2}-[0-9a-f]{6}$/;

export async function GET(
  _req: NextRequest,
  ctx: Ctx,
): Promise<Response> {
  try {
    const projectId = await requireProjectIdFromParams(ctx.params);

    const resolved = await awaitParams(ctx.params);
    const compositionId = resolved.compositionId;
    if (
      typeof compositionId !== "string" ||
      !COMPOSITION_ID_REGEX.test(compositionId)
    ) {
      throw new WorkbenchError(
        ErrorCode.VALIDATION_FAILED,
        "Invalid composition id",
        { input: compositionId, expected: COMPOSITION_ID_REGEX.source },
      );
    }

    let raw: string | null = null;

    // Phase 3: try Neon first
    if (isNeonConfigured()) {
      try {
        // compositionId = "scene-05-88ea72" → hexTail = "88ea72"
        const hexTailMatch = compositionId.match(/scene-\d+-([a-z0-9]{6})$/);
        if (hexTailMatch) {
          const hexTail = hexTailMatch[1];
          const rows = await sql<{ html_content: string | null }>`
            SELECT html_content
            FROM content_analyzer.scenes
            WHERE project_id = ${projectId}
              AND scene_id LIKE ${'sc_' + hexTail + '%'}
          `;
          if (rows[0]?.html_content) {
            raw = rows[0].html_content;
          }
        }
      } catch (err) {
        console.warn("[composition/scenes/id] Neon read failed, falling back to FS:", err instanceof Error ? err.message : err);
      }
    }

    // Local FS fallback
    if (!raw) {
      const absPath = resolveProjectFile(
        projectId,
        "composition",
        "compositions",
        compositionId + ".html",
      );
      try {
        raw = await fs.readFile(absPath, "utf-8");
      } catch (e: unknown) {
        if ((e as NodeJS.ErrnoException)?.code === "ENOENT") {
          throw new WorkbenchError(
            ErrorCode.COMPOSITION_NOT_FOUND,
            "Sub-composition file not found",
            { projectId, compositionId },
          );
        }
        throw e;
      }
    }

    if (!raw) {
      throw new WorkbenchError(
        ErrorCode.COMPOSITION_NOT_FOUND,
        "Sub-composition not found",
        { projectId, compositionId },
      );
    }

    // Defence-in-depth: reject any forbidden token before we echo bytes
    // into a live-rendered HTML document. This should never fire because
    // the composition pipeline already scans before writing to disk.
    const scan = scanHtml(raw);
    if (!scan.ok) {
      throw new WorkbenchError(
        ErrorCode.UNKNOWN,
        "Sub-composition contains forbidden token",
        { projectId, compositionId, hit: scan.hit },
      );
    }

    // The generator appends `-template` to the <template>'s id, while the
    // inner <div> keeps the plain compositionId. We look up the template by
    // the suffixed id, but register/play timelines by the plain compId.
    const tplIdLiteral = JSON.stringify(compositionId + "-template");
    const compIdLiteral = JSON.stringify(compositionId);
    const host = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<base target="_blank">
<title>${compositionId}</title>
<style>
html, body { margin: 0; background: #111; color: #fff; overflow: hidden; font-family: system-ui, sans-serif; height: 100%; }
/*
 * HyperFrames scenes are authored at their native resolution (default
 * 1920x1080, taken from the inner <div>'s data-width/data-height).
 * Iframes hosting the preview are typically smaller, so without
 * scaling the right/bottom edges are clipped. We:
 *   1. Read the authored stage size from the inner #{compositionId}
 *      container's data-width/data-height (fallback 1920x1080).
 *   2. Wrap that container in a #hf-stage element pinned to the top
 *      left, and apply transform: scale(s) where s fits the stage
 *      into the viewport while preserving aspect ratio (letterboxed).
 *   3. Re-run the scaler on window resize so the preview feels right
 *      when Dale resizes the drawer / devtools.
 */
#hf-stage {
  position: absolute;
  top: 50%;
  left: 50%;
  transform-origin: center center;
  /* Scale + center is applied imperatively by fitStage() */
}
</style>
<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>
</head>
<body>
${raw}
<script>
(function () {
  var tplId = ${tplIdLiteral};
  var compId = ${compIdLiteral};

  function fitStage() {
    var stage = document.getElementById("hf-stage");
    if (!stage) return;
    var inner = stage.firstElementChild;
    if (!inner) return;
    var authoredW = parseFloat(inner.getAttribute("data-width")) || 1920;
    var authoredH = parseFloat(inner.getAttribute("data-height")) || 1080;
    // Pin authored dimensions on the wrapper so scale() has a known box.
    stage.style.width = authoredW + "px";
    stage.style.height = authoredH + "px";
    var vw = window.innerWidth;
    var vh = window.innerHeight;
    var s = Math.min(vw / authoredW, vh / authoredH);
    // Translate by -50% of authored size so the stage centres around
    // the body midpoint after scaling.
    stage.style.transform =
      "translate(-50%, -50%) scale(" + s + ")";
  }

  function mount() {
    var tpl = document.getElementById(tplId);
    if (!tpl || !tpl.content) {
      console.warn("Template not found:", tplId);
      return;
    }
    var clone = tpl.content.cloneNode(true);
    // cloneNode copies <script> nodes but does NOT execute them per HTML spec.
    // Replace each with a fresh <script> so the browser runs the contents.
    var scripts = clone.querySelectorAll("script");
    scripts.forEach(function (oldScript) {
      var newScript = document.createElement("script");
      for (var i = 0; i < oldScript.attributes.length; i++) {
        var attr = oldScript.attributes[i];
        newScript.setAttribute(attr.name, attr.value);
      }
      newScript.textContent = oldScript.textContent;
      oldScript.parentNode.replaceChild(newScript, oldScript);
    });
    // Wrap the template content in a #hf-stage element so we can scale
    // it without touching the scene's internal layout.
    var stage = document.createElement("div");
    stage.id = "hf-stage";
    stage.appendChild(clone);
    document.body.appendChild(stage);

    fitStage();
    window.addEventListener("resize", fitStage);

    window.dispatchEvent(new Event("hyperframes:ready"));

    // The re-created <script> has already run synchronously above, so the
    // timeline should now be registered on window.__timelines.
    try {
      var tl = window.__timelines && window.__timelines[compId];
      if (tl && typeof tl.play === "function") {
        tl.play();
      } else {
        console.warn("No timeline registered for:", compId);
      }
    } catch (e) {
      console.error("Failed to play timeline:", e);
    }
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", mount);
  } else {
    mount();
  }
})();
</script>
</body>
</html>`;

    return new Response(host, {
      status: 200,
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Cache-Control": "no-store",
      },
    });
  } catch (e) {
    return respondError(e);
  }
}
